vim.keymap.set("n", "<leader>ff", ":Telescope find_files<cr>", {})
vim.keymap.set("n", "<leader>lgr", ":Telescope live_grep<cr>", {})
vim.keymap.set("n", "<leader>fb", ":Telescope buffers<cr>", {})
vim.keymap.set("n", "<leader>ht", ":Telescope help_tags<cr>", {})
vim.keymap.set("n", "<leader>grs", ":Telescope grep_string<cr>", {})
